# Generated by Django 6.0.3 on 2026-03-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
